# SIMPLE STRATEGY TABLE

StrategyTable:

  TwoSameCards:
    2:
      8: 'H'
      2: 'Sp'
    3:
      8: 'H'
      2: 'Sp'
    4:
      7: 'H'
      5: 'Sp'
      2: 'H'
    5:
      10: 'H'
      2: 'D'
    6:
      8: 'H'
      2: 'Sp'
    7:
      9: 'H'
      2: 'Sp'
    8: 'Sp'
    9:
      10: 'St'
      8: 'Sp'
      7: 'St'
      2: 'Sp'
    10: 'St'
    1: 'Sp'

  Ace:
    2:
      7: 'H'
      5: 'D'
      2: 'H'
    3:
      7: 'H'
      4: 'D'
      2: 'H'
    4:
      7: 'H'
      4: 'D'
      2: 'H'
    5:
      7: 'H'
      4: 'D'
      2: 'H'
    6:
      7: 'H'
      3: 'D'
      2: 'H'
    7:
      9: 'H'
      7: 'St'
      2: 'D'
    8:
      7: 'St'
      6: 'D'
      2: 'St'
    9: 'St'

  Other:
    5: 'H'
    6: 'H'
    7: 'H'
    8: 'H'
    9:
      7: 'H'
      2: 'D'
    10:
      10: 'H'
      2: 'D'
    11: 'D'
    12:
      7: 'H'
      4: 'St'
      2: 'H'
    13:
      7: 'H'
      2: 'St'
    14:
      7: 'H'
      2: 'St'
    15:
      7: 'H'
      2: 'St'
    16:
      7: 'H'
      2: 'St'
    17: 'St'
    18: 'St'
    19: 'St'
    20: 'St'
    21: 'St'