# Hearts, Diamonds, Clubs, Spade
suits:
  - H
  - D
  - C
  - S

# Possible card ranks
ranking:
  - A
  - '2'
  - '3'
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
  - '9'
  - '10'
  - J
  - K
  - Q

# card ranks and values mapping
card_val:
  A: [1, 11]
  '2': 2
  '3': 3
  '4': 4
  '5': 5
  '6': 6
  '7': 7
  '8': 8
  '9': 9
  '10': 10
  'J': 10
  'Q': 10
  'K': 10
